export const SET_USER = 'SET_USER';

export const GET_LEAGUES_REQUEST = 'GET_LEAGUES_REQUEST';
export const GET_LEAGUE_REQUEST = 'GET_LEAGUE_REQUEST';
export const GET_LEAGUES_SUCCESS = 'GET_LEAGUES_SUCCESS';
export const GET_LEAGUE_SUCCESS = 'GET_LEAGUE_SUCCESS';
export const GET_CLUBS_BY_LEAGUE = 'GET_CLUBS_BY_LEAGUE';

export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST';
export const GET_COUNTRY_BY_LEAGUE_REQUEST = 'GET_COUNTRY_BY_LEAGUE_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_BY_LEAGUE_SUCCESS = 'GET_COUNTRY_BY_LEAGUE_SUCCESS';

export const GET_CLUBS_REQUEST = 'GET_CLUBS_REQUEST';
export const GET_CLUB_REQUEST = 'GET_CLUB_REQUEST';
export const GET_VALIDCLUBS_REQUEST = 'GET_VALIDCLUBS_REQUEST';
export const GET_CLUBS_SUCCESS = 'GET_CLUBS_SUCCESS';
export const GET_CLUB_SUCCESS = 'GET_CLUB_SUCCESS';
export const GET_VALIDCLUBS_SUCCESS = 'GET_VALIDCLUBS_SUCCESS';

export const GET_ROSTERS_REQUEST = 'GET_ROSTERS_REQUEST';
export const GET_ROSTERS_SUCCESS = 'GET_ROSTERS_SUCCESS';
export const INSERT_PLAYER_TO_ROSTER_REQUEST =
  'INSERT_PLAYER_TO_ROSTER_REQUEST';
export const INSERT_PLAYER_TO_ROSTER_SUCCESS =
  'INSERT_PLAYER_TO_ROSTER_SUCCESS';

export const DELETE_PLAYER_FROM_ROSTER_REQUEST =
  'DELETE_PLAYER_FROM_ROSTER_REQUEST';
export const DELETE_PLAYER_FROM_ROSTER_SUCCESS =
  'DELETE_PLAYER_FROM_ROSTER_SUCCESS';

export const GET_PLAYERS_FOR_SEARCH_REQUEST = 'GET_PLAYERS_FOR_SEARCH_REQUEST';
export const GET_PLAYERS_FOR_SEARCH_SUCCESS = 'GET_PLAYERS_FOR_SEARCH_SUCCESS';

export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYER_REQUEST = 'GET_PLAYER_REQUEST';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';
export const ADD_PLAYER_REQUEST = 'ADD_PLAYER_REQUEST';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const EDIT_PLAYER_REQUEST = 'EDIT_PLAYER_REQUEST';
export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS';

export const GET_FREE_AGENTS_REQUEST = 'GET_FREE_AGENTS_REQUEST';
export const GET_FREE_AGENTS_SUCCESS = 'GET_FREE_AGENTS_SUCCESS';

export const GET_DRAFT_REQUEST = 'GET_DRAFT_REQUEST';
export const GET_DRAFT_SUCCESS = 'GET_DRAFT_SUCCESS';
export const GET_DRAFT_PLAYERS_BY_COUNTRY_REQUEST =
  'GET_DRAFT_PLAYERS_BY_COUNTRY_REQUEST';
export const GET_DRAFT_PLAYERS_BY_COUNTRY_SUCCESS =
  'GET_DRAFT_PLAYERS_BY_COUNTRY_SUCCESS';

export const GET_SEASONS = 'GET_SEASONS';

export const SEARCH_PLAYER_REQUEST = 'SEARCH_PLAYER_REQUEST';
export const SEARCH_PLAYER_SUCCESS = 'SEARCH_PLAYER_SUCCESS';

export const GET_CHAMP_BY_SEASON_AND_LEAGUE_REQUEST =
  'GET_CHAMP_BY_SEASON_AND_LEAGUE_REQUEST';
export const GET_CHAMP_BY_SEASON_AND_LEAGUE_SUCCESS =
  'GET_CHAMP_BY_SEASON_AND_LEAGUE_SUCCESS';

export const ACCESS_ERROR = 'ACCESS_ERROR';
