export const SET_USER = 'SET_USER';

export const GET_LEAGUES = 'GET_LEAGUES';
export const GET_LEAGUE = 'GET_LEAGUE';
export const GET_CLUBS_BY_LEAGUE = 'GET_CLUBS_BY_LEAGUE';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_COUNTRY_BY_LEAGUE = 'GET_COUNTRY_BY_LEAGUE';

export const GET_CLUBS = 'GET_CLUBS';
export const GET_CLUB = 'GET_CLUB';

export const GET_ROSTERS = 'GET_ROSTERS';
export const INSERT_PLAYER_TO_ROSTER = 'INSERT_PLAYER_TO_ROSTER';
export const DELETE_PLAYER_FROM_ROSTER = 'DELETE_PLAYER_FROM_ROSTER';

export const GET_PLAYERS_FOR_SEARCH = 'GET_PLAYERS_FOR_SEARCH';

export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYER = 'GET_PLAYER';
export const ADD_PLAYER = 'ADD_PLAYER';

export const GET_FREE_AGENTS = 'GET_FREE_AGENTS';

export const GET_SEASONS = 'GET_SEASONS';

export const SEARCH_PLAYER = 'SEARCH_PLAYER';
